version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:0.22.1
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -s src/ -d docs/
      - run:
          name: "Test Website"
          command: htmlproofer docs/ --allow-hash-href --check-html --empty-alt-ignore --disable-external
      - store_artifacts:
          path: docs
      - add_ssh_keys
      - deploy:
          commands:
            - git add docs
            - git commit -m "autocommit from circleci"
            - git push git@github.com:florianroulet/MyBlog.git $CIRCLE_SHA1:master

#    deployment:
#      production:
#        branch: master
#        commands:
#          - git add docs
#          - git commit -m "autocommit from circleci"
#          - git push git@github.com:florianroulet/MyBlog.git $CIRCLE_SHA1:master
