baseURL = "https://florianroulet.github.io/MyBlog/"
languageCode = "en-us"
title = "My super blog !"
theme = "hugo-theme-cactus-plus"
tags = ["developer", "maker", "blog"]
config = "config.toml"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[params]
    tagline = "Florian Roulet's personnal blog"
    description = "Full-stack developer and maker enthusiast based in Tours, FR."
    logoBig = "/images/osprey-logo.png"
    logoSmall = "/images/osprey-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "FlorianRoulet"
    linkedin = ""
    github = "florianroulet"
    email = ""
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[social]
  twitter-square = "https://twitter.com/FlorianRoulet"
  github-square = "https://github.com/florianroulet"
