baseurl = "https://florianroulet.github.io/MyBlog/"
title = "Personnal thoughts"
languageCode = "en-us"

enableEmoji = true


[[menu.main]]
        name    = "Home"
        url             = "/"
        weight  = -1

[[menu.main]]
        name    = "Blog"
        url             = "/blog/"
        weight  = 10

[social]
twitter = "FlorianRoulet"
